name: Build Artifact
on: [workflow_dispatch]

jobs:
  build:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          repository: fa-total-mayhem
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: fa-total-mayhem
          path: build

